process.chdir(require('path').resolve(__dirname,'..'));
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
class El{constructor(){this.textContent='';this.value='';this.children=[];this.style={setProperty(){}};this.attrs={};this.dataset={};this.classList={add(){},remove(){},toggle(){}};this.open=false;this.handlers={}}set innerHTML(s){this.children=s.includes('<span>')?Array.from({length:5},()=>new El):s.includes('<ol>')?[new El]:[]}get firstChild(){return this.children[0]}setAttribute(k,v){this.attrs[k]=v}append(e){this.children.push(e)}replaceChildren(...e){this.children=e}addEventListener(e,cb){this.handlers[e]=cb}getBoundingClientRect(){}focus(){}select(){}getContext(){return new Proxy({},{get:()=>()=>{}})}showModal(){this.open=true}close(){this.open=false;this.handlers.close?.()}}
const els={};const doc={hidden:false,getElementById:id=>els[id]??=new El,querySelector:()=>new El,querySelectorAll:()=>[],createElement:()=>new El,addEventListener(){}};let now=0,tick;const ctx=vm.createContext({document:doc,window:{},performance:{now:()=>now},setInterval:f=>tick=f,setTimeout:()=>0,clearTimeout(){},matchMedia:q=>({matches:q.includes('reduced-motion')}),Math,Set,Globes:{draw(){},reset(){},reveal(){}},AdventureAudio:{resume(){},pause(){},success(){},duck(){},newQuestion(){},unlock:()=>Promise.resolve(true),toggle:()=>false,volume(){},skip(){}},CountryGallery:{render(){}}});
vm.runInContext(fs.readFileSync('assets/js/data.js','utf8')+'\n'+fs.readFileSync('assets/js/app.js','utf8'),ctx);
const state=()=>vm.runInContext('({index,clueCount,remaining,resolved,stars:discovered.size})',ctx);function advance(ms){now+=ms;tick()}
assert.equal(vm.runInContext('level',ctx),null);advance(60000);assert.equal(state().clueCount,0);
vm.runInContext("chooseLevel('easy')",ctx);assert.equal(els.choices.children.length,4);assert.equal(vm.runInContext('queue.length',ctx),195);
advance(14999);assert.equal(state().clueCount,0);advance(1);assert.equal(state().clueCount,1);for(let i=2;i<=5;i++){advance(15000);assert.equal(state().clueCount,i);assert.equal(state().resolved,false)}advance(14999);assert.equal(state().resolved,false);advance(1);assert.equal(state().resolved,true);assert.equal(state().stars,1);advance(15000);assert.equal(state().clueCount,5);
els.next.onclick();assert.equal(state().clueCount,0);els.pause.onclick();advance(60000);assert.equal(state().remaining,15000);els.pause.onclick();doc.hidden=true;advance(60000);assert.equal(state().remaining,15000);doc.hidden=false;els.parents.onclick();advance(60000);assert.equal(state().remaining,15000);els.settings.close();
vm.runInContext("chooseLevel('medium')",ctx);assert.equal(els.choices.children.length,4);assert.equal(vm.runInContext('new Set(queue).size===queue.length',ctx),true);assert.equal(vm.runInContext('queue.some(i=>discovered.has(i))',ctx),false);
vm.runInContext("chooseLevel('high')",ctx);assert.equal(els.choices.children.length,4);els.answer.value='wrong';els['answer-form'].handlers.submit({preventDefault(){}});assert.equal(state().resolved,false);els.answer.value=vm.runInContext('COUNTRIES[index].name.toUpperCase()+"!"',ctx);els['answer-form'].handlers.submit({preventDefault(){}});assert.equal(state().resolved,true);assert.equal(state().stars,2);
vm.runInContext("showLevels()",ctx);const old=state().remaining;advance(60000);assert.equal(state().remaining,old);assert.equal(state().stars,2);
vm.runInContext(`if(COUNTRIES.length!==195)throw Error('coverage');for(const c of COUNTRIES){if(c.clues.length!==5||!c.path.startsWith('M')||!c.capital||!c.region||!c.aliases.includes(c.name)||!Number.isFinite(c.lat))throw Error(c.name);for(const mode of ['easy','medium','high']){level=mode;const clues=makeClues(c);if(clues.length!==5)throw Error('clue count');if(clues.some(text=>/flag/i.test(text)||text.includes(c.flag)))throw Error('flag clue '+c.name);if((mode==='easy'||mode==='medium')&&!clues[0].includes(c.clues[0])&&!clues[0].includes(c.neighbors[0]||'no land-border neighbors'))throw Error('missing discovery fact '+c.name)}}`,ctx);

// Every level must produce four distinct choices, with exactly one correct choice.
vm.runInContext(`for(const mode of ['easy','medium','high']){level=mode;for(let i=0;i<COUNTRIES.length;i++){index=i;makeChoices();const options=[...$('choices').children].map(b=>Number(b.dataset.country));if(options.length!==4||new Set(options).size!==4||!options.includes(index))throw Error('choices '+mode+' '+i)}}`,ctx);
vm.runInContext(`discovered.clear();const first=new Set();for(let i=0;i<30;i++){chooseLevel('easy');first.add(index);if(new Set(queue).size!==195)throw Error('queue duplicates')}if(first.size<10)throw Error('insufficient shuffle variation')`,ctx);
// All 195 countries can be completed without a repeated question.
vm.runInContext(`discovered.clear();chooseLevel('high');const seen=new Set();for(let n=0;n<195;n++){if(seen.has(index))throw Error('repeated country');seen.add(index);finish(true);$('next').onclick()}if(level!==null||discovered.size!==195)throw Error('completion gate')`,ctx);
// Manual hints count toward the same five-clue limit and cannot reveal while paused.
vm.runInContext(`chooseLevel('medium');paused=true;clue();if(clueCount)throw Error('paused clue');paused=false;for(let n=0;n<5;n++)$('early-clue').onclick();if(clueCount!==5||resolved)throw Error('manual hint cap');$('early-clue').onclick();if(clueCount!==5||resolved)throw Error('extra manual clue')`,ctx);
advance(14999);assert.equal(state().resolved,false);advance(1);assert.equal(state().resolved,true);
// Prefer a gentle installed English voice, while allowing a grown-up to choose another.
const spoken=[];ctx.window.speechSynthesis={getVoices:()=>[{name:'Albert',lang:'en-US'},{name:'Samantha',lang:'en-US'}],cancel(){},speak:u=>spoken.push(u)};
ctx.SpeechSynthesisUtterance=function(text){this.text=text};
vm.runInContext("sound=true;speak('Hello, Sattwik!')",ctx);
assert.equal(spoken.at(-1).voice.name,'Samantha');assert.equal(spoken.at(-1).rate,.9);assert.equal(spoken.at(-1).pitch,1.02);
els['voice-choice'].value='Albert|en-US';vm.runInContext("speak('Let’s explore!')",ctx);assert.equal(spoken.at(-1).voice.name,'Albert');
console.log('PASS: 195 complete records; level gate; 4 choices for all 585 country/level combinations; randomized decks; complete 195-country journey; five 15-second clues and reveal; pause/hidden/dialog; answer normalization; retained progress; manual clue cap; warm voice selection.');
